# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true

exclude_paths:
  - 'tests/*'
  - 'docs-generator/*'
  - 'blueprints/*'
  - 'scripts/*'
  - 'lib/*'
  - 'packages/*/tests/*'
  - 'packages/*/blueprints/*'
  - 'packages/*/bin/*'
  - 'packages/*/lib/*'
  - 'packages/unpublished-test-infra/*'
  - 'packages/private-build-infra/*'

version: '2' # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false # we should re-enable this and slowly reduce to ~750 over time
  method-complexity:
    enabled: false # we should re-enable this and slowly reduce to ~10 over time
  method-count:
    config:
      threshold: 50
  return-statements:
    enabled: false
  method-lines:
    config:
      threshold: 100
  identical-code:
    enabled: true
